### ISSUE TITLE
Crash while starting the app

### ISSUE THREAD

**Issue by ArtanBerisha1** [ben-xD/posenet#1]
I am unable to run the app, I don't know for sure where is the problem, I get the following error:
2020-10-12 15:50:26.537 7129-7129/org.tensorflow.lite.examples.posenet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.posenet, PID: 7129
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.tensorflow.lite.examples.posenet/org.tensorflow.lite.examples.posenet.ProfilePoseNetActivity}: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.lite.examples.posenet.ProfilePoseNetActivity" on path: DexPathList[[zip file "/data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/lib/arm64, /data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.lite.examples.posenet.ProfilePoseNetActivity" on path: DexPathList[[zip file "/data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/lib/arm64, /data/app/org.tensorflow.lite.examples.posenet-htIeMrbEG6PdVH38l-Y7qQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3183)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by uxduck** [comment]
Hey,

Sorry, I removed that old Activity from the project but did not remove it from the manifest. I fixed it now, and also uploaded a test video (`/raw/circle_cut.mp4`) in the `/raw` folder. It is referenced as `R.raw.circle_cut`, feel free to change this video with your own.

Just pull the latest changes from master, and it should work.

**Comment by ArtanBerisha1** [comment]
@ben-xD Thanks, now its not crashing :) 
But after running it now I just get color green on my feed, it shows interpreter time but not the video, also I have some other questions like: where does it saves the video that it process, or do you have any video showing how this app works because I am not so sure.

Thank you

**Comment by uxduck** [comment]
It doesn't save the video, it just runs the poseNet on a video file located in your app. Im not sure why you get a green color instead of seeing the video, can you share a screenshot.

If you replace `R.raw.circle_cut` with your own video file of a person, you should see a skeleton drawing on the video whilst it plays. This is goal of the modification of the demo app.

**Comment by ArtanBerisha1** [comment]
Yes I also replaced` R.raw.circle_cut `with my own video named test.mp4 that I put into raw folder, and instead of circle_cut now its `R.raw.test` , and this is the result from both videos.

I also resized the video in 640x480 but its still showing the same problem

Also would it be hard to save the video ? 

![121534227_3566602050069234_5736251214667798345_n](https://user-images.githubusercontent.com/56814499/95952816-14af9080-0df9-11eb-9cf2-5154170cf80c.png)

**Comment by uxduck** [comment]
Oh I just realised, i hardcoded the resolution... 😅  Sorry.

If you change the resolution in PoseNetFragment.kt (line 90, 91) to the resolution of your video. 
```java
    private val PREVIEW_WIDTH = 640
    private val PREVIEW_HEIGHT = 480
```

In terms of saving the file, if you can find a way to capture the surface I am drawing the skeleton to a file, it might just be enough. I don't have the time to think about that now, but I think the code in PosenetFragment is relatively readable, so you could try and let me know how it goes.

**Comment by ArtanBerisha1** [comment]
I don't think this is the issue here, because I also used a video with 640x480 resolution, I also tried with your video but its still the same issue. 
Then I added another video with 1920x1080 resolution and changed the resolution in the line 90,91 in PosenetFragment.kt.
Today I have more time and if I can I will try to debug it more to try to find the issue.
Just one more question, is this working in your device ?

**Comment by uxduck** [comment]
Yes it's working for me, I tested it when I removed the bug in the manifest.

**Comment by ArtanBerisha1** [comment]
I changed the device and its working , I am not sure why. Also there was a problem with cropping the frame before processing with posenet(maybe generalize this part), I think I could make a PR about this part.
Another question does this implementation takes the frame as soon as is available, so if in one device the interpreter time is 200ms and in another 50ms , the second device is going to process more frames right?

Also the green screen is shown in devices with Qualcomm CPU , no idea why :/

**Comment by uxduck** [comment]
1. Nice observation about the Qualcomm issue. The video playing is not tensorflow related, its just using MediaPlayer. Maybe you can try and copy only the mediaplayer/ surface related code to a separate app which doesn't use tensorflow, as see if you have the same issue? (perhaps ExoPlayer is a library that helps people avoid issues like this, im just guessing here, i never used it)

2. The PoseNet code wants to take the whole frame, resizes it for the model, and resizes it back to overlay it nicely over the video. How are you cropping the video, we might need to make the skeleton drawing code aware of this? I'm not sure what you mean by "a problem" though.

3. Yes you're right about the processing. A faster phone will finish the frame sooner, which makes the main thread available again to process another call of `imageAvailableListener`. I think it is using the fact that the CPU is busy to prevent a backlog of old frames queuing up. This code is not great, as things could be moved onto the background thread.
